org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.caching=true

minecraft_version=1.21.1
neo_version=21.1.227
moddev_version=2.0.78
japicmp_plugin_version=0.4.6

api_group=com.cybersammy.bugreport
api_artifact=bugreport-api
api_version=0.2.0
api_baseline_version=0.2.0
api_baseline_sha256=FBE38D3A7A6A7A744E6902F606498F6C953B9B322E65C7B8EDD5C0B776D9093B
mod_version=0.0.1-spike
junit_version=5.11.4
junit_platform_version=1.11.4
