package com.cybersammy.bugreport.core.workspace;

import com.cybersammy.bugreport.api.identifier.CategoryId;
import com.cybersammy.bugreport.api.identifier.ProviderId;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;

/** Deterministic result of executing the generated diagnostics for one category. */
public record CategoryGeneratedDiagnosticResult(
        ProviderId providerId,
        CategoryId categoryId,
        List<GeneratedDiagnosticOutcome> outcomes,
        long retainedBytes) {
    public CategoryGeneratedDiagnosticResult {
        Objects.requireNonNull(providerId, "providerId");
        Objects.requireNonNull(categoryId, "categoryId");
        outcomes = List.copyOf(Objects.requireNonNull(outcomes, "outcomes"));
        if (outcomes.stream().anyMatch(Objects::isNull)) {
            throw new IllegalArgumentException("Generator outcomes must not contain null");
        }
        for (int index = 1; index < outcomes.size(); index++) {
            if (Comparator.comparing(GeneratedDiagnosticOutcome::generatorId)
                            .compare(outcomes.get(index - 1), outcomes.get(index))
                    >= 0) {
                throw new IllegalArgumentException(
                        "Generator outcomes must be strictly ordered by generator ID");
            }
        }
        long actualBytes = outcomes.stream()
                .flatMap(outcome -> outcome.result().stream())
                .mapToLong(GeneratedDiagnosticResult::byteCount)
                .reduce(0L, Math::addExact);
        if (retainedBytes < 0 || retainedBytes != actualBytes) {
            throw new IllegalArgumentException("Retained generated byte total is inconsistent");
        }
        outcomes.stream().flatMap(outcome -> outcome.result().stream()).forEach(result -> {
            if (!providerId.equals(result.providerId()) || !categoryId.equals(result.categoryId())) {
                throw new IllegalArgumentException(
                        "Generated result provenance does not match its category result");
            }
        });
    }
}
