package com.cybersammy.bugreport.core.workspace;

/** Stable failure classification for one generated diagnostic invocation. */
public enum GeneratedDiagnosticCode {
    PROVIDER_NOT_REGISTERED,
    PROVIDER_DISABLED,
    CATEGORY_NOT_DECLARED,
    GENERATOR_NOT_DECLARED,
    GENERATOR_NOT_USED_BY_CATEGORY,
    UNSUPPORTED_SIDE,
    CONTENT_TYPE_MISMATCH,
    DUPLICATE_ARTIFACT_ID,
    ARTIFACT_COUNT_EXCEEDED,
    ARTIFACT_BYTE_LIMIT_EXCEEDED,
    TOTAL_BYTE_LIMIT_EXCEEDED,
    COLLECTION_BYTE_LIMIT_EXCEEDED,
    CALLBACK_TIMED_OUT,
    EXECUTION_CONTEXT_UNAVAILABLE,
    CANCELLED,
    INVALID_TEXT,
    PROVIDER_FAILURE,
    WORKSPACE_CHANGED,
    DESTINATION_ALREADY_EXISTS,
    ATOMIC_MOVE_UNSUPPORTED,
    IO_FAILURE,
    ROLLBACK_FAILED
}
