modLoader="javafml"
loaderVersion="[4,)"
license="Apache-2.0"

[[mods]]
modId="bugreport"
version="${version}"
displayName="Bug Report API Packaging Spike"
description='''M0 prototype for optional API Jar-in-Jar packaging.'''

[[dependencies.bugreport]]
modId="neoforge"
type="required"
versionRange="[21.1.227,)"
ordering="NONE"
side="BOTH"

[[dependencies.bugreport]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"
